[theme]
# 💡 สีปุ่ม/ไฮไลท์/เส้นใต้: ใช้สีส้มทองสดใส เพิ่มลูกเล่นให้ดูเด่นและตื่นตัว
primaryColor = "#FFC570"          

# 💡 สีพื้นหลังหลัก (ขวา): ใช้สีครีมทองอ่อนๆ ให้ความรู้สึกนุ่มนวล สบายตา ไม่สว่างจ้าเกินไป
backgroundColor = "#EBEFF5"       

# 💡 สีของ Sidebar และกล่องสี่เหลี่ยม: ใช้สีน้ำเงินเข้มขรึม เพื่อให้ข้อมูลผู้ใช้และเมนูลอยเด่นขึ้นมาอย่างทรงพลัง
secondaryBackgroundColor = "#1A3263" 

# 💡 สีตัวอักษร: ใช้สีขาวนวล (หรือจะใช้สี #EFD2B0) เพื่อให้ตัดกับพื้นหลังกล่องสีน้ำเงินเข้มและอ่านง่ายชัดเจน
textColor = "#FFFFFF"
